name: transit_dart

description: >-
  Transit is a data format and set of libraries for conveying values between
  applications written in different languages. This library provides support for
  marshalling Transit data to/from Dart.

version: 0.8.60

repository: https://github.com/wevre/transit-dart

environment:
  sdk: '>=2.19.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  async: ^2.11.0
  big_decimal: ^0.5.0
  collection: ^1.17.1
  typed_data: ^1.3.1
