name: transit
description: A starting point for Dart libraries or applications.
version: 0.8.0-alpha
repository: https://github.com/wevre/transit-dart

environment:
  sdk: '>=2.19.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  big_decimal: ^0.5.0
  collection: ^1.17.1
  uuid: ^3.0.7
